### PR TITLE
Sin exponent reduction

### PR DESCRIPTION
**Pull request by AYadrov**
Updated version of ival-sin implementation.
Exponent analysis of endpoints is added to the logic. 
It allows to speedup ival-sin and return a result at the beginning with almost no calculations.
These cases are:
If at the analysis stage we can figure out by looking at exponents of endpoints that the distance between them is greater than 2pi -> return [-1, 1].
If at the analysis stage we can conclude that exponents are nan/inf values -> return [-1, 1].
If at the analysis stage we can conclude that two endpoints are within the range (-1, 1) - return ((monotonic bfsin) x).
If at the ananysis stage we can conclude that two endpoints are within the range [2, 4) or [-2, -4) - return ((comonotonic bfsin) x).

### CODE REVIEW

**Comment by AYadrov** [comment]
The comment to the logic can be found at the "Cleanup" commit

**Comment by pavpanchekha** [comment]
Just to summarize discussion today, we decided to move the tricky exponent logic into its own function, `(classify-ival-periodic <ival> exp)` which returns a classification as a symbol, like maybe `near-0` or `too-wide` or `range-reduce` or something like that. Then the `ival-sin`, `ival-tan`, and `ival-cos` functions can call `classify-ival-periodic` and just match on the result, removing a lot of duplication. I think we'll also be able to inline `ival-sin-default` into `ival-sin` since there should now only be one call to it, and similar for other trig functions.

**Comment by AYadrov** [comment]
Reviewed by Research Assistant Yadrov.
"Encouraged to merge" - Research Assistant Yadrov

**Review by pavpanchekha — APPROVED** [review]
Any idea how much faster it is?

**Comment by AYadrov** [comment]
For Herbie the results are:
main branch - total time per operation
```
ival-sin 527.17s
ival-cos 406.33s
ival-tan 126.86s
```
branch with exponent-reduction modifications:
```
ival-sin 385.82s
ival-cos 394.32s
ival-tan 91.48s
```
For Rival's benchmarks the results are:
main
```
ival-sin             [  19.045,   19.392]
ival-cos             [  17.634,   17.900]
ival-tan             [  18.585,   18.725]
```
sin-exponent-reduction
```
ival-sin             [  16.136,   16.532]
ival-cos             [  14.108,   14.425]
ival-tan             [  11.526,   11.727]
```

**Pull request merged**
